# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  app:
    image: dotnet-webapp-sample
    build:
      context: .
    ports:
      - 8080:80
